//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturaElectSaiOpen.tfhk_Adjuntos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CargarAdjuntos", Namespace="http://schemas.datacontract.org/2004/07/ServiceSoap.UBL2._0.Models.Object")]
    [System.SerializableAttribute()]
    public partial class CargarAdjuntos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] archivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enviarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string formatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] archivo {
            get {
                return this.archivoField;
            }
            set {
                if ((object.ReferenceEquals(this.archivoField, value) != true)) {
                    this.archivoField = value;
                    this.RaisePropertyChanged("archivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string enviar {
            get {
                return this.enviarField;
            }
            set {
                if ((object.ReferenceEquals(this.enviarField, value) != true)) {
                    this.enviarField = value;
                    this.RaisePropertyChanged("enviar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string formato {
            get {
                return this.formatoField;
            }
            set {
                if ((object.ReferenceEquals(this.formatoField, value) != true)) {
                    this.formatoField = value;
                    this.RaisePropertyChanged("formato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroDocumentoField, value) != true)) {
                    this.numeroDocumentoField = value;
                    this.RaisePropertyChanged("numeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoField, value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadAttachmentResponse", Namespace="http://schemas.datacontract.org/2004/07/ServiceSoap.UBL2._0.Response")]
    [System.SerializableAttribute()]
    public partial class UploadAttachmentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] mensajesValidacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                if ((this.codigoField.Equals(value) != true)) {
                    this.codigoField = value;
                    this.RaisePropertyChanged("codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeField, value) != true)) {
                    this.mensajeField = value;
                    this.RaisePropertyChanged("mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] mensajesValidacion {
            get {
                return this.mensajesValidacionField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajesValidacionField, value) != true)) {
                    this.mensajesValidacionField = value;
                    this.RaisePropertyChanged("mensajesValidacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.resultadoField, value) != true)) {
                    this.resultadoField = value;
                    this.RaisePropertyChanged("resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="tfhk_Adjuntos.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CargarAdjuntos", ReplyAction="http://tempuri.org/IService/CargarAdjuntosResponse")]
        FacturaElectSaiOpen.tfhk_Adjuntos.UploadAttachmentResponse CargarAdjuntos(string tokenEmpresa, string tokenPassword, FacturaElectSaiOpen.tfhk_Adjuntos.CargarAdjuntos adjunto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CargarAdjuntos", ReplyAction="http://tempuri.org/IService/CargarAdjuntosResponse")]
        System.Threading.Tasks.Task<FacturaElectSaiOpen.tfhk_Adjuntos.UploadAttachmentResponse> CargarAdjuntosAsync(string tokenEmpresa, string tokenPassword, FacturaElectSaiOpen.tfhk_Adjuntos.CargarAdjuntos adjunto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : FacturaElectSaiOpen.tfhk_Adjuntos.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<FacturaElectSaiOpen.tfhk_Adjuntos.IService>, FacturaElectSaiOpen.tfhk_Adjuntos.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FacturaElectSaiOpen.tfhk_Adjuntos.UploadAttachmentResponse CargarAdjuntos(string tokenEmpresa, string tokenPassword, FacturaElectSaiOpen.tfhk_Adjuntos.CargarAdjuntos adjunto) {
            return base.Channel.CargarAdjuntos(tokenEmpresa, tokenPassword, adjunto);
        }
        
        public System.Threading.Tasks.Task<FacturaElectSaiOpen.tfhk_Adjuntos.UploadAttachmentResponse> CargarAdjuntosAsync(string tokenEmpresa, string tokenPassword, FacturaElectSaiOpen.tfhk_Adjuntos.CargarAdjuntos adjunto) {
            return base.Channel.CargarAdjuntosAsync(tokenEmpresa, tokenPassword, adjunto);
        }
    }
}
